samba:
  image: joebiellik/samba-server

  volumes:
    # You must provide a Samba config file
    - ./smb.conf:/etc/samba/smb.conf

    # Shares
    - ~/projects:/mnt/projects
    - ~/videos:/mnt/videos:ro

  ports:
    - "137:137/udp"
    - "138:138/udp"
    - "139:139/tcp"
    - "445:445/tcp"

  environment:
    - USERNAME=joe
    - PASSWORD=samba

    # Uncomment to override defaults
    # - UID=1000
    # - GID=1000
