#!/bin/bash
source /tmp/lakkris.env
OIFS=$IFS
IFS=$'\n'

# Wait for all services
for service in 'serf'; do
	while [[ ! -d "/var/run/s6/services/${service}" || $(s6-svstat -u "/var/run/s6/services/${service}") != "true" ]]; do
		sleep 1s
	done
done

SVCS=( $(serf members -format=json | jq -c --raw-output '.members[]|select(.status=="failed")') )
for DATA in ${SVCS[@]}; do
	NAME=$(echo "${DATA}" | jq -c --raw-output '.name')
	STATUS=$(echo "${DATA}" | jq -c --raw-output '.status')
	if [[ "${STATUS}" == "failed" && -n "${NAME}" && "${NAME}" != "null" ]]; then
		serf force-leave "${NAME}"
	fi
done

IFS=$OIFS
