#!/usr/bin/with-contenv bash

for x in '/run/nginx' '/config/nginx' '/config/nginx/log' '/var/lib/nginx' '/var/lib/nginx/tmp'; do
	if [[ ! -d ${x} ]]; then
		mkdir ${x}
	fi
#	chown nginx:nginx ${x}
	chown -R abc:abc ${x}
done


sed -i 's@/var/log/nginx/@/config/nginx/log/@g' /etc/nginx/nginx.conf
sed -i 's@user nginx;@user abc;@g' /etc/nginx/nginx.conf

cat > /etc/nginx/conf.d/default.conf <<-EOF
server {
  listen ${SET_PORT:-80};
  root /app;
  index index.php index.html index.htm;
  server_name _;
  client_max_body_size 200M;

  location ${SET_URLBASE:-}/public {
    expires 365d;
    access_log off;
  }
  location ${SET_URLBASE:-}/(.git|data|app|modules|resources|vendor) {
    deny all;
  }
  location ${SET_URLBASE:-}/ {
    rewrite ^ ${SET_URLBASE:-}/index.php last;
  }
  # pass the PHP scripts to FastCGI server listening on /var/run/php-fpm.sock
  location = ${SET_URLBASE:-}/index.php {
    fastcgi_pass unix:/var/run/php-fpm.sock;
    fastcgi_index index.php;
    fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
    include fastcgi_params;
  }
}
EOF
