dist: bionic

language: bash

services:
- docker

addons:
  apt:
    update: true
    sources:
    - sourceline: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
      key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - jq

env:
  global:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  - DOCKER_ORG=lostlakkris
  matrix:
  - CONTAINER=sonarr
  - CONTAINER=radarr
  - CONTAINER=lidarr
  - CONTAINER=lazylibrarian
  - CONTAINER=nzbget
  - CONTAINER=nzbhydra
  - CONTAINER=tautulli
  - CONTAINER=plex
  - CONTAINER=organizr
#  - CONTAINER=shinobi
#  - CONTAINER=serf

before_install:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json

before_script:
- sudo bash hooks/pre_build

script:
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" &> /dev/null
- export DOCKERFILE_PATH=Dockerfile.${CONTAINER}
- export DOCKER_REPO=index.docker.io/${DOCKER_ORG}/${CONTAINER}
- export DOCKER_TAG=latest
- export IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}
- bash hooks/build
- bash hooks/push
