dist: bionic

language: bash

services:
- docker

adons:
  apt:
    update: true
    packages:
    - docker-ce

env:
  global:
  - DOCKER_CLI_EXPERIMENTAL=enabled

matrix:
  include:
  - env:
    - CONTAINER=sonarr
    - FROM=linuxserver/sonarr
  - env:
    - CONTAINER=radarr
    - FROM=linuxserver/radarr
  - env:
    - CONTAINER=lidarr
    - FROM=linuxserver/lidarr
  - env:
    - CONTAINER=lazylibrarian
    - FROM=linuxserver/lazylibrarian
  - env:
    - CONTAINER=nzbget
    - FROM=linuxserver/nzbget
  - env:
    - CONTAINER=nzbhydra
    - FROM=linuxserver/hydra2
  - env:
    - CONTAINER=plex
    - FROM=linuxserver/plex
  - env:
    - CONTAINER=tautulli
    - FROM=linuxserver/tautulli
  - env:
    - CONTAINER=organizr
    - FROM=
  - env:
    - CONTAINER=shinobi
    - FROM=

before_install:
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update -q
- sudo apt-get install -y docker-ce docker-ce-cli containerd.io
- sudo curl -L https://raw.githubusercontent.com/johanhaleby/bash-templater/master/templater.sh -o /usr/local/bin/templater
- sudo chmod +x /usr/local/bin/templater

script: ./build.sh
