sudo: required
services:
  - docker
language: bash

env:
    global:
      - TRAVIS_SECURE_ENV_VARS=true

before_install:
  - sudo apt-get remove docker docker-engine docker.io
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
  - sudo service docker restart
  - mkdir ~/.docker
  - echo '{"experimental":"enabled"}' | tee ~/.docker/config.json
  - ls -al ~/.docker/config.json
  - cat ~/.docker/config.json

script:
  - bash build.sh $TRAVIS_REPO_SLUG $DOCKER_USERNAME $DOCKER_PASSWORD index.docker.io
