dist: bionic

language: bash

services:
- docker

adons:
  apt:
    update: true
    packages:
    - docker-ce

env:
  global:
  - DOCKER_CLI_EXPERIMENTAL=enabled

matrix:
  include:
  - env:
    - CONTAINER=sonarr
    - FROM=linuxserver/sonarr
  - env:
    - CONTAINER=radarr
    - FROM=linuxserver/radarr
  - env:
    - CONTAINER=lidarr
    - FROM=linuxserver/lidarr
  - env:
    - CONTAINER=lazylibrarian
    - FROM=linuxserver/lazylibrarian
  - env:
    - CONTAINER=nzbget
    - FROM=linuxserver/nzbget
  - env:
    - CONTAINER=nzbhydra
    - FROM=linuxserver/hydra2
  - env:
    - CONTAINER=organizr
    - FROM=organizrtools/organizr-v2
  - env:
    - CONTAINER=plex
    - FROM=linuxserver/plex
  - env:
    - CONTAINER=tautulli
    - FROM=linuxserver/tautulli
  - env:
    - CONTAINER=shinobi
    - FROM=

script: ./build.sh
