dist: bionic

language: bash

services:
- docker

adons:
  apt:
    update: true
    packages:
    - docker-ce
    - qemu-user-static

env:
  global:
  - DOCKER_CLI_EXPERIMENTAL=enabled
  matrix:
  - CONTAINER=sonarr
  - CONTAINER=radarr
  - CONTAINER=lidarr
  - CONTAINER=lazylibrarian
  - CONTAINER=nzbget
  - CONTAINER=nzbhydra
  - CONTAINER=tautulli
  - CONTAINER=plex
  - CONTAINER=shinobi
  - CONTAINER=organizr

before_install:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update -q
- sudo apt-get install -y docker-ce docker-ce-cli containerd.io
- sudo apt-get install -y qemu-user-static
- sudo docker run --rm --privileged multiarch/qemu-user-static:register
- sudo docker run --privileged linuxkit/binfmt:v0.6

script:
- ./build.sh
