os: linux
dist: bionic
language: shell
services:
  - docker
addons:
  apt:
    update: true
    sources:
      - sourceline: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic
          stable
        key_url: https://download.docker.com/linux/ubuntu/gpg
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - qemu-user
      - jq
      - git
before_install:
  - bash .travis/before_install
before_script:
  - bash .travis/before_script
script:
  - travis_retry bash .travis/script
env:
  global:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - DOCKER_ORG=lostlakkris
stages:
  - name: build
    if: type != cron
  - name: meta
    if: type != cron
  - name: cron
jobs:
  include:
    - stage: meta
      before_install: bash .travis/meta before_install
      before_script: bash .travis/meta before_script
      script: travis_retry bash .travis/meta script
    - stage: cron
      before_install: bash .travis/cron before_install
      before_script: bash .travis/cron before_script
      script: travis_retry bash .travis/cron script
    - stage: build
      env: CONTAINER=autoheal
    - stage: build
      env: CONTAINER=esphome
    - stage: build
      env: CONTAINER=git-sync
