---
version: 0.0.{build}

image:
- Ubuntu1804

environment:
  matrix:
    - ARCH: amd64
  docker_user:
    secure: TJfOg4mQbXKqm629vAB2Gw==
  docker_password:
    secure: xeG9nOJrO9D//Wv8/gvLPg==

skip_commits:
  files:
    - '*.md'

build_script:
- sh: >-
    for z in $(ls -1 Dockerfiles/*.amd64); do
      x=$(echo "${z}" | cut -d'/' -f2-)
      echo ${x}
      docker build --pull --no-cache -t "lostlakkris/${x%.*}:latest" -t "lostlakkris/${x%.*}:${ARCH}" -f ${z} .
      if [ $? -ne 0 ]; then
        exit 2
      fi
    done

#test_script:
deploy_script:
- sh: docker login -u ${docker_user} -p ${docker_password}
- sh: >-
    for z in $(ls -1 Dockerfiles/*.amd64); do
      x=$(echo "${z}" | cut -d'/' -f2-)
      echo ${x}
      docker push "lostlakkris/${x%.*}"
    done
