---
version: 0.0.{build}

image:
- Ubuntu1804

environment:
  global:
    DOCKER_CLI_EXPERIMENTAL: enabled
    DOCKER_ORG: lostlakkris
    DOCKER_USER:
      secure: TJfOg4mQbXKqm629vAB2Gw==
    DOCKER_PASSWORD:
      secure: xeG9nOJrO9D//Wv8/gvLPg==
  matrix:
  - CONTAINER: sonarr
  - CONTAINER: radarr
  - CONTAINER: lidarr
  - CONTAINER: lazylibrarian
  - CONTAINER: nzbget
  - CONTAINER: nzbhydra
  - CONTAINER: tautulli
  - CONTAINER: plex
  - CONTAINER: organizr
#  - CONTAINER: shinobi

skip_commits:
  files:
    - '*.md'

install:
- echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
- sudo bash hooks/pre_build

build_script:
- docker login -u "${DOCKER_USER}" -p "${DOCKER_PASSWORD}" &> /dev/null
- export DOCKERFILE_PATH=Dockerfile.${CONTAINER}
- export DOCKER_REPO=index.docker.io/${DOCKER_ORG}/${CONTAINER}
- export DOCKER_TAG=latest
- export IMAGE_NAME=${DOCKER_REPO}:${DOCKER_TAG}
- bash hooks/build
- bash hooks/push
