FROM organizrtools/organizr-v2:latest
ENV SET_SERVICE="organizr" \
    SET_PORT="80"
LABEL "lostlakkris.service"="organizr"
COPY s6.lakkris/ /

HEALTHCHECK --interval=30s --timeout=3s --start-period=5m \
  CMD /scripts/healthcheck.sh || exit 1
