FROM linuxserver/radarr:latest
ENV SET_SERVICE="radarr" \
    SET_PORT="7878" \
    LOSTLAKKRIS_CONTENT="movies"
LABEL "lostlakkris.service"="radarr" \
      "lostlakkris.content"="movies"
COPY s6.lakkris/ /

HEALTHCHECK --interval=2m --timeout=3s \
  CMD /scripts/healthcheck.sh || exit 1
