FROM linuxserver/hydra2:latest
ENV SET_SERVICE="nzbhydra" \
    SET_PORT="5076"
LABEL "lostlakkris.service"="nzbhydra"
RUN apt-get update -y && \
    apt-get install -y jq python-pip && \
    pip install yq && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*
COPY s6.lakkris/ /

HEALTHCHECK --interval=30s --timeout=3s --start-period=5m \
  CMD /scripts/healthcheck.sh || exit 1
