version: '2.4'

#networks:
#  testing:

services:
  serf:
    build:
      context: .
      dockerfile: Dockerfiles/serf.amd64
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  nginx:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/var/run/docker.sock:/tmp/docker.sock:ro"
    environment:
      DEFAULT_HOST: "organizr"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  organizr:
    build:
      context: .
      dockerfile: Dockerfiles/organizr.amd64
    depends_on:
    - nginx
    - serf
    volumes:
    - "./config/organizr:/config"
    environment:
      VIRTUAL_HOST: "organizr"
      VIRTUAL_PORT: "80"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  nzbget:
    build:
      context: .
      dockerfile: Dockerfiles/nzbget.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/nzbget:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  nzbhydra:
    build:
      context: .
      dockerfile: Dockerfiles/nzbhydra.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/nzbhydra:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  sonarr:
    build:
      context: .
      dockerfile: Dockerfiles/sonarr.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/sonarr:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  radarr:
    build:
      context: .
      dockerfile: Dockerfiles/radarr.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/radarr:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  lidarr:
    build:
      context: .
      dockerfile: Dockerfiles/lidarr.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/lidarr:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  lazylibrarian:
    build:
      context: .
      dockerfile: Dockerfiles/lazylibrarian.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/lazylibrarian:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  plex:
    build:
      context: .
      dockerfile: Dockerfiles/plex.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/plex:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  tautulli:
    build:
      context: .
      dockerfile: Dockerfiles/tautulli.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/tautulli:/config"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
  shinobi:
    build:
      context: .
      dockerfile: Dockerfiles/shinobi.amd64
    depends_on:
    - organizr
    - serf
    volumes:
    - "./config/shinobi:/config"
    - "./config/shinobi-videos:/opt/shinobi/videos"
    dns: 172.17.0.1
    dns_search: weave.local
    network_mode: bridge
