FROM lsiobase/alpine:3.11

RUN apk add --no-cache bash git tini openssh jq curl
COPY s6.git-sync/ /

VOLUME ["/data", "/update-hooks"]

ENV SET_SERVICE="git-sync"
LABEL "lostlakkris.service"="git-sync"
COPY s6.lakkris/ /

#ENTRYPOINT [ "tini", "-g", "--" ]
#CMD [ "/opt/bin/git-sync.sh" ] ## Replaced with s6 service file
