FROM linuxserver/nzbget:latest
ENV SET_SERVICE="nzbget" \
    SET_PORT="6789"
LABEL "lostlakkris.service"="nzbget"
COPY s6.lakkris/ /

HEALTHCHECK --interval=2m --timeout=3s \
  CMD /scripts/healthcheck.sh || exit 1
