FROM organizrtools/organizr-v2:latest
ENV SET_SERVICE="organizr" \
    SET_PORT="80"
LABEL "lostlakkris.service"="organizr"
COPY s6.lakkris/ /

HEALTHCHECK --interval=2m --timeout=3s \
  CMD /scripts/healthcheck.sh || exit 1
