FROM linuxserver/nzbget:latest
ENV SET_SERVICE="nzbget" \
    SET_PORT="6789"
LABEL "lostlakkris.service"="nzbget"
COPY s6.lakkris/ /

HEALTHCHECK --interval=30s --timeout=3s --start-period=4m \
  CMD /scripts/healthcheck.sh || exit 1
