FROM lsiobase/alpine:3.11

RUN apk add --no-cache bash jq curl samba-server samba-common-tools openssl
COPY s6.samba/ /

EXPOSE 137/udp 138/udp 139/tcp 445/tcp

ENV SET_SERVICE="samba" \
    USERNAME="samba" \
    PASSWORD="password" \
    UID="1000" \
    GID="1000"
LABEL "lostlakkris.service"="samba"
COPY s6.lakkris/ /
