FROM linuxserver/tautulli:latest
ENV SET_SERVICE="tautulli"
LABEL "lostlakkris.service"="tautulli"
RUN pip install --no-cache-dir -U crudini
COPY s6.lakkris/ /

HEALTHCHECK --interval=5m --timeout=3s \
  CMD /scripts/healthcheck.sh || exit 1
