FROM linuxserver/lazylibrarian:latest
ENV SET_SERVICE="lazylibrarian" \
    SET_PORT="5299" \
    LOSTLAKKRIS_CONTENT="books"
LABEL "lostlakkris.service"="lazylibrarian" \
      "lostlakkris.content"="books"
RUN apt-get update && \
    apt-get install --no-install-recommends -y crudini && \
    apt-get -y autoremove && \
    rm -rf /var/lib/apt/lists/*
COPY s6.lakkris/ /

HEALTHCHECK --interval=30s --timeout=3s \
  CMD /scripts/healthcheck.sh || exit 1
