#!/bin/bash

source /tmp/lakkris.env
CONFIG_FILE="/config/nzbget.conf"
DATA_ROOT="/downloads/completed"
if [[ ! -e ${CONFIG_FILE} ]]; then
	exit 0
fi

HASH_START=$(md5sum ${CONFIG_FILE} | awk '{print $1}')
# TODO: Toggle-able scope to servername
SERVICES=( $(serf members -format=json | jq -c --raw-output '.members[]') )
for SERVICE_DATA in ${SERVICES[@]}; do
	SERVERNAME=$(echo "${SERVICE_DATA}" | jq -c --raw-output '.tags.LAKKRIS_SERVERNAME')
	SERVICE_NAME=$(echo "${SERVICE_DATA}" | jq -c --raw-output '.tags.LAKKRIS_SERVICE')
	SERVICE_CONTENT=$(echo "${SERVICE_DATA}" | jq -c --raw-output '.tags.LAKKRIS_CONTENT')
	if [[ -n "${SERVICE_CONTENT}" && "${SERVICE_CONTENT}" != "null" && "${SERVICE_CONTENT}" != "nzb" ]]; then
		Name="${SERVERNAME}-${SERVICE_CONTENT}"
		DestDir="\${DestDir}/${SERVERNAME}/${SERVICE_CONTENT}"
		Unpack="yes"
		Aliases=$(echo "$Name" | tr '[A-Z]' '[a-z]')
		# Check if category and directory exists
		for x in "${DATA_ROOT}" "${DATA_ROOT}/${SERVERNAME}" "${DATA_ROOT}/${SERVERNAME}/${SERVICE_CONTENT}"; do
			if [[ ! -d "${x}" ]]; then
				mkdir -p "${x}"
				chown $(id -u abc):$(id -g abc) "${x}"
			fi
		done
		if ! grep -q "^Category.*\.Name=${Name}$" "${CONFIG_FILE}"; then
			# Get last category
			CATEGORY=$(awk -F '.' '/^Category/{print $1}' ${CONFIG_FILE} | sed 's@Category@@g' | sort -nur | head -n 1)
			NEW_CATEGORY=$(( ${CATEGORY} + 1 ))
			echo "Category${NEW_CATEGORY}.Name=${Name}" >> ${CONFIG_FILE}
			echo "Category${NEW_CATEGORY}.DestDir=${DestDir}" >> ${CONFIG_FILE}
			echo "Category${NEW_CATEGORY}.Unpack=${Unpack}" >> ${CONFIG_FILE}
			echo "Category${NEW_CATEGORY}.Aliases=${Aliases}" >> ${CONFIG_FILE}
		fi
	fi
done
HASH_END=$(md5sum ${CONFIG_FILE} | awk '{print $1}')
if [[ ("${HASH_START}" != "${HASH_END}") && $(s6-svstat -u "/var/run/s6/services/${LAKKRIS_SERVICE}") ]]; then
	s6-svc -h "/var/run/s6/services/${LAKKRIS_SERVICE}"
fi
