#!/bin/bash
(
	source /tmp/lakkris.env
	if [[ -x "/lakkris/post/${LAKKRIS_SERVICE}.sh" ]]; then
		# Wait for serf to be up and running
		while [[ ! -d "/var/run/s6/services/serf" || $(s6-svstat -u "/var/run/s6/services/serf") != "true" ]]; do
			sleep 1s
		done
		# Execute the post-start script
		bash /lakkris/post/${LAKKRIS_SERVICE}.sh
		bash /lakkris/misc/serf-tags.sh
	fi
) &
