#!/usr/bin/with-contenv bash
if [[ ! -d /config/shinobi ]]; then
	mkdir /config/shinobi
fi
# Base shinobi
for x in 'conf' 'super'; do
	if [[ ! -e /config/shinobi/${x}.json ]]; then
		cp /opt/shinobi/${x}.sample.json /config/shinobi/${x}.json
	fi
	if [[ ! -e /opt/shinobi/${x}.json ]]; then
		ln -s /config/shinobi/${x}.json /opt/shinobi/${x}.json
	fi
done

# Motion
if [[ ! -e /config/shinobi/motion.conf ]]; then
	cp /opt/shinobi/plugins/motion/conf.sample.json /config/shinobi/motion.json
fi
if [[ ! -e /opt/shinobi/plugins/motion/conf.json ]]; then
	ln -s /config/shinobi/motion.json /opt/shinobi/plugins/motion/conf.json
fi

git pull -q /opt/shinobi

chown -R abc:abc \
	/opt/shinobi

chown -R abc:abc \
	/config/shinobi

chown -R abc:abc \
	/dev/shm/streams
