#!/usr/bin/with-contenv bash
(
	source /tmp/environment.vars
	case ${SET_SERVICE} in
		"nzbhydra")
			echo "== service: ${SET_SERVICE}"
			YML_FILE="/config/nzbhydra.yml"
			SET_SERVICE='nzbhydra2'
			;;
		*)
			echo "== Not a sonarr-derivative."
			exit 0;
			;;
	esac
	# Wait for the service to come up and the config file to be created
	while [[ ! -e ${YML_FILE} || ! -d "/var/run/s6/services/${SET_SERVICE}" || $(s6-svstat -u "/var/run/s6/services/${SET_SERVICE}") != "true" ]]; do
		sleep 1s
	done
	# Check for some known config variables to see if the files been created
	while [[ ! -e ${YML_FILE} || -z "$(grep 'urlBase' ${YML_FILE})" || -z "$(grep 'port' ${YML_FILE})" || -z "$(grep 'apiKey' ${YML_FILE})" ]]; do
		sleep 1s
	done

	# Modify nzbhydra.yml and restart service if it changed
	MD5_START=$(md5sum ${YML_FILE} | awk '{print $1}')

	OPTIONS=( $(yq -c --raw-output '.main|keys[]' "${YML_FILE}") )

	for OPTION in ${OPTIONS[@]}; do
		ENVIRONMENT="SET_$(echo "${OPTION}" | tr '[a-z]' '[A-Z]')"
		if [[ -n "${!ENVIRONMENT}" ]]; then
			if [[ ! -e /tmp/svc_${SET_SERVICE}.yml ]]; then
				cp ${YML_FILE} /tmp/svc_${SET_SERVICE}.yml
			fi
			yq -y --arg opt "${OPTION}" --arg val "${!ENVIRONMENT}" '.main[$opt]=$val' /tmp/svc_${SET_SERVICE}.yml > /tmp/svc_${SET_SERVICE}.yml.2
			mv /tmp/svc_${SET_SERVICE}.yml.2 /tmp/svc_${SET_SERVICE}.yml
		fi
	done

	MD5_END=$(md5sum /tmp/svc_${SET_SERVICE}.yml | awk '{print $1}')
	if [[ "${MD5_START}" != "${MD5_END}" ]]; then
		s6-svc -wD -d "/var/run/s6/services/${SET_SERVICE}"
		s6-svwait -d "/var/run/s6/services/${SET_SERVICE}"
		mv /tmp/svc_${SET_SERVICE}.yml "${YML_FILE}"
		s6-svc -wU -u "/var/run/s6/services/${SET_SERVICE}"
		s6-svwait -u "/var/run/s6/services/${SET_SERVICE}"
	fi
) &
