#!/bin/bash
source /tmp/lakkris.env
CONFIG_FILE="/config/nginx/site-confs/default"
LAKKRIS_FILE="/config/nginx/lakkris.conf"
while [[ ! -e "${CONFIG_FILE}" ]]; do
	exit 0
done

if [[ ! -d /config/nginx/lakkris ]]; then
	mkdir /config/nginx/lakkris
fi

if [[ ! -e /config/nginx/lakkris/000-authblock.conf ]]; then
	cp /lakkris/tmpl/nginx/000-authblock.conf /config/nginx/lakkris/000-authblock.conf
fi
touch /config/nginx/lakkris.conf

CONTENT="include /config/nginx/lakkris.conf;"

CONFIG_MD5_START=$(md5sum ${CONFIG_FILE} ${LAKKRIS_FILE} | awk '{print $1}')
grep -q -x -F "${CONTENT}" ${CONFIG_FILE} || sed -i "s#^}#${CONTENT}\n}#g" ${CONFIG_FILE}

SERVICES=( $(serf members -format=json | jq -c --raw-output '.members[]') )
if [[ ${#SERVICES[@]} -gt 0 && -e /config/nginx/lakkris/000-authblock.conf ]]; then
        rm /config/nginx/lakkris/100-*.conf
fi
for SERVICE_DATA in ${SERVICES[@]}; do
        SERVERNAME=$(echo "${SERVICE_DATA}" | jq -c --raw-output '.tags.LAKKRIS_SERVERNAME')
        SERVICE_NAME=$(echo "${SERVICE_DATA}" | jq -c --raw-output '.tags.LAKKRIS_SERVICE')
        WEBROOT=$(echo "${SERVICE_DATA}" | jq -c --raw-output '.tags.LAKKRIS_WEBROOT')
        if [[ (-n "${WEBROOT}" || "${SERVICE_NAME}" == "nzbget") && -e /lakkris/tmpl/nginx/${SERVICE_NAME}.conf ]]; then
                echo "${SERVICE_DATA}" | jq -c --raw-output '.tags | to_entries[] | (.key | ascii_upcase) + "=" + .value' > /tmp/service.env
                templater /lakkris/tmpl/nginx/${SERVICE_NAME}.conf -f /tmp/service.env -s > "/config/nginx/lakkris/100-${SERVERNAME}-${SERVICE_NAME}.conf"
        fi
done
if [[ -e /tmp/service.env ]]; then
        rm /tmp/service.env
fi

cat $(ls /config/nginx/lakkris/* | sort -n) > ${LAKKRIS_FILE}

CONFIG_MD5_END=$(md5sum ${CONFIG_FILE} ${LAKKRIS_FILE} | awk '{print $1}')

if [[ "${CONFIG_MD5_START}" != "${CONFIG_MD5_END}" && $(s6-svstat -u "/var/run/s6/services/nginx") ]]; then
	s6-svc -h "/var/run/s6/services/nginx"
fi

