#!/bin/bash
## This script waits through the startup process for various stages to be completed
(
	source /tmp/lakkris.env
	SERVICE=${LAKKRIS_SERVICE}
	SCRIPT=${LAKKRIS_SERVICE}
	# Set some overrides if container calls things differently
	case "${LAKKRIS_SERVICE}" in
		"organizr")
			SERVICE="nginx"
			SCRIPT="${LAKKRIS_SERVICE}"
			;;
		"nzbhydra")
			SERVICE="nzbhydra2"
			SCRIPT="${LAKKRIS_SERVICE}"
			;;
		*)
			;;
	esac
	# Wait for the S6 services directory to be created
	while [ ! -d /var/run/s6/services ] ; do
		sleep 1s
	done
	sleep 5s
	# Wait for the serf and targetted service directory to exist
	while [[ ! -d /var/run/s6/services/serf && ! -d "/var/run/s6/services/${SERVICE}" ]] ; do
		sleep 1s
	done

	# Use S6 to wait for the services
	s6-svwait -u "/var/run/s6/services/serf" "/var/run/s6/services/${SERVICE}"
	# Recheck that the services are up
	while ! s6-svstat -u "/var/run/s6/services/serf" && ! s6-svstat -u "/var/run/s6/services/${SERVICE}" ; do
		sleep 1s
	done
	bash /lakkris/.notify/serf-tags.sh

	# Check if the port is responding
	if [[ -n "${LAKKRIS_PORT}" ]]; then
		while ! nc -z 127.0.0.1 ${LAKKRIS_PORT} ; do
			sleep 1s
		done
	fi
	sleep 5s
	# Configure self now
	if [[ -x "/lakkris/.config/${SCRIPT}.sh" ]]; then
		bash "/lakkris/.config/${SCRIPT}.sh"
	fi
)&
