#!/bin/bash
source /tmp/lakkris.env

case "${LAKKRIS_SERVICE}" in
	"organizr")
		if [[ -d /config/nginx/lakkris ]]; then
			rm -f /config/nginx/lakkris/*
		fi
		if [[ -d /config/nginx/tmp ]]; then
			rm -f /config/nginx/tmp/*
		fi
		;;
	*)
		echo "No prestart cleanup overrides for ${LAKKRIS_SERVICE}"
		;;
esac
