#!/bin/bash
echo "/tmp/lakkris.notify:c,/lakkris/events-notify/inotifyd.sh" >> /tmp/lakkris.notify
echo "/tmp/lakkris.notify:x,/lakkris/events-notify/inotifyd.sh" >> /tmp/lakkris.notify
(
	source /tmp/lakkris.env
	# Execute the post-start script
	if [[ -x /lakkris/start-post/inotifyd.sh ]]; then
		bash /lakkris/start-post/inotifyd.sh
	fi
)&
