#!/usr/bin/with-contenv bash
sql_preseed='/tmp/mysql-first-time.sql'
if [[ -z "${MYSQL_ROOT_PASSWORD}" ]]; then
	MYSQL_ROOT_PASSWORD="password"
fi

start_mysql(){
#	/usr/bin/mysqld_safe --user=abc --datadir=/config/mysql --init-file="$sql_preseed" &
	/usr/bin/mysqld --user=abc --datadir=/config/mysql --init-file="$sql_preseed" &
	pid="$!"
	RET=1
	while [[ $RET -ne 0 ]]; do
		/usr/bin/mysql -uroot -p"${MYSQL_ROOT_PASSWORD}" -e "status" > /dev/null 2>&1
		RET=$?
		sleep 1
	done
}

if [[ ! -d /config/mysql ]]; then
	cat > "$sql_preseed" <<-EOSQL
	DELETE FROM mysql.user ;
	EOSQL

	# add rest of sql commands based on password set or not
	cat >> "$sql_preseed" <<-EONEWSQL
	CREATE USER 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}' ;
	GRANT ALL ON *.* TO 'root'@'%' WITH GRANT OPTION ;
	DROP DATABASE IF EXISTS test ;
	EONEWSQL

	cat /opt/shinobi/sql/user.sql >> ${sql_preseed}
	echo "" >> ${sql_preseed}
	cat /opt/shinobi/sql/framework.sql >> ${sql_preseed}

	mysql_install_db --user=abc --datadir=/config/mysql

	start_mysql
	/usr/bin/mysqladmin -u root -p"${MYSQL_ROOT_PASSWORD}" shutdown
	wait "$pid"
	echo "Database Setup Completed"
	rm ${sql_preseed}
fi

chown -R abc:abc \
	/config/mysql
