#!/bin/bash
set -e
DOCKER_REPO=linuxserver/radarr

bash .travis/listDockerTags ${DOCKER_REPO} | awk '/^v/ && /-ls/ && !/-[a-km-rt-z]/' > /tmp/${CONTAINER}.VERSIONS

# Set LATEST
sort -V /tmp/${CONTAINER}.VERSIONS | tail -n 1 > LATEST

# Add 1 missing to VERSIONS
ADDED=0
if [[ ! -e VERSIONS ]]; then
        touch VERSIONS
fi
for x in $( sort -V /tmp/${CONTAINER}.VERSIONS ); do
        if ! grep -q "^${x}$" VERSIONS; then
                if [[ ${ADDED} -eq 0 ]]; then
                        echo ${x} >> VERSIONS
                        ADDED=1
                else
                        break
                fi
        fi
done
if [[ -e /tmp/${CONTAINER}.VERSIONS ]]; then
	rm /tmp/${CONTAINER}.VERSIONS
fi
