#!/usr/bin/with-contenv bash
case ${SET_SERVICE} in
	"sonarr"|"radarr"|"lidarr")
		echo "== service: ${SET_SERVICE}"
		;;
	*)
		echo "== Not a sonarr-derivative."
		exit 0;
		;;
esac

(
	source /tmp/environment.vars
	# Wait for the config file to be created
	while [[ ! -d "/var/run/s6/services/${SET_SERVICE}" || ! -e /config/config.xml ]]; do
		sleep 1s
	done
	while [[ ! -d "/var/run/s6/services/${SET_SERVICE}" || $(s6-svstat -u "/var/run/s6/services/${SET_SERVICE}") != "true" ]]; do
		sleep 1s
	done
	while [[ ! -e /config/config.xml || -z "$(grep 'UrlBase' /config/config.xml)" || -z "$(grep 'Port' /config/config.xml)" || -z "$(grep 'ApiKey' /config/config.xml)" ]]; do
		sleep 1s
	done
	# Modify config.xml and restart service if it changed
	MD5_START=$(md5sum /config/config.xml | awk '{print $1}')

	CONFIG=(
		"s@<UrlBase>.*</UrlBase>@<UrlBase>${SET_URLBASE}</UrlBase>@g"
		"s@<Port>.*</Port>@<Port>${SET_PORT}</Port>@g"
	)
	if [[ -n "${SET_APIKEY}" ]]; then
		CONFIG+=("s@<ApiKey>.*</ApiKey>@<ApiKey>${SET_APIKEY}</ApiKey>@g")
	fi

	for STRING in ${CONFIG[@]}; do
		sed -i "${STRING}" /config/config.xml
	done

	MD5_END=$(md5sum /config/config.xml | awk '{print $1}')
	if [[ "${MD5_START}" != "${MD5_END}" ]]; then
		s6-svc -h "/var/run/s6/services/${SET_SERVICE}"
	fi
) &
