#!/usr/bin/with-contenv bash

for x in '/config/webtrees'; do
	if [[ ! -d ${x} ]]; then
		mkdir ${x}
		chown abc:abc ${x}
		chmod 777 ${x}
	fi
done

chown -R abc:abc \
	/app

if [[ ! -L /app/data && -d /app/data && -d /config/webtrees ]]; then
	find /app/data -type f -exec mv {} /config/webtrees/ \;
	rmdir /app/data
fi

if [[ ! -L /app/data ]]; then
	ln -s /config/webtrees /app/data
fi

if [[ -e /config/webtrees/config.ini.php ]]; then
	if ! grep -q '^rewrite_urls=' /config/webtrees/config.ini.php; then
		echo 'rewrite_urls="1"' >> /config/webtrees/config.ini.php
	fi
fi
