#!/usr/bin/with-contenv bash
(
	source /tmp/environment.vars
	case ${SET_SERVICE} in
		"lazylibrarian"|"tautulli")
			echo "[lakkris] service: ${SET_SERVICE}"
			INI_FILE="/config/config.ini"
			INI_SECTION="General"
			;;
		*)
			echo "[lakkris] Not an ini-based configuration."
			exit 0;
			;;
	esac

	# Wait for the service to come up and the config file to be created
	while [[ ! -e ${INI_FILE} || ! -d "/var/run/s6/services/${SET_SERVICE}" || $(s6-svstat -u "/var/run/s6/services/${SET_SERVICE}") != "true" ]]; do
		sleep 1s
	done
	# Check for some known config variables to see if the files been created
	while [[ ! -e ${INI_FILE} || -z "$(grep 'http_root' ${INI_FILE})" || -z "$(grep 'http_port' ${INI_FILE})" || -z "$(grep 'api_key' ${INI_FILE})" ]]; do
		sleep 1s
	done

	# Modify config.ini and restart service if it changed
	MD5_START=$(md5sum ${INI_FILE} | awk '{print $1}')

	OPTIONS=( $(crudini --get "${INI_SECTION}" ${INI_FILE}) )

	for OPTION in ${OPTIONS[@]}; do
		ENVIRONMENT="SET_$(echo "${OPTION}" | tr '[a-z]' '[A-Z]')"
		if [[ -n "${!ENVIRONMENT}" ]]; then
			echo "[lakkris] Config override detected: ${OPTION}"
			crudini --set ${INI_FILE} General "${OPTION}" "${!ENVIRONMENT}"
		fi
	done

	MD5_END=$(md5sum ${INI_FILE} | awk '{print $1}')
	if [[ "${MD5_START}" != "${MD5_END}" ]]; then
		s6-svc -h "/var/run/s6/services/${SET_SERVICE}"
	fi
) &
