#!/usr/bin/with-contenv bash
(
	source /tmp/environment.vars
	case ${SET_SERVICE} in
		"sonarr"|"radarr"|"lidarr")
			echo "[lakkris] service: ${SET_SERVICE}"
			XML_FILE="/config/config.xml"
			;;
		*)
			echo "[lakkris] Not an xml-based configuration."
			exit 0;
			;;
	esac

	# Wait for the service to come up and the config file to be created
	while [[ ! -e ${XML_FILE} || ! -d "/var/run/s6/services/${SET_SERVICE}" || $(s6-svstat -u "/var/run/s6/services/${SET_SERVICE}") != "true" ]]; do
		sleep 1s
	done
	# Check for some known config variables to see if the files been created
	while [[ ! -e ${XML_FILE} || -z "$(grep 'UrlBase' ${XML_FILE})" || -z "$(grep 'Port' ${XML_FILE})" || -z "$(grep 'ApiKey' ${XML_FILE})" ]]; do
		sleep 1s
	done

	# Modify config.xml and restart service if it changed
	MD5_START=$(md5sum ${XML_FILE} | awk '{print $1}')

	OPTIONS=( $(awk '!/Config/' ${XML_FILE} | sed 's@.*<\(.*\)>\(.*\)</\(.*\)>@\1@g') )

	for OPTION in ${OPTIONS[@]}; do
		ENVIRONMENT="SET_$(echo "${OPTION}" | tr '[a-z]' '[A-Z]')"
		if [[ -n "${!ENVIRONMENT}" ]]; then
			echo "[lakkris] Config override detected: ${OPTION}"
			sed -i "s@<${OPTION}>.*</${OPTION}>@<${OPTION}>${!ENVIRONMENT}</${OPTION}>@g" ${XML_FILE}
		fi
	done

	MD5_END=$(md5sum ${XML_FILE} | awk '{print $1}')
	if [[ "${MD5_START}" != "${MD5_END}" ]]; then
		s6-svc -h "/var/run/s6/services/${SET_SERVICE}"
	fi
) &
