#!/bin/bash
STAGE="before_script"
export DOCKER_CLI_EXPERIMENTAL=enabled

echo "[***] ${STAGE} - Info about the OS"
cat /etc/*-release

source .travis/common

echo "[***] ${STAGE} - Adding qemu-user-static container, and binfmt"
docker run --rm --privileged multiarch/qemu-user-static:register --reset
docker run --privileged linuxkit/binfmt:v0.7
echo
