#!/bin/bash
if [[ -z "${CONTAINER}" ]]; then
        echo "[***] ${STAGE} - \${CONTAINER} WAS UNDEFINED. WHAT DO I BUILD?"
        exit 1
fi

echo "[***] ${STAGE} - PWD: ${PWD}"
echo "[***] ${STAGE} - TRAVIS_BUILD_DIR: ${TRAVIS_BUILD_DIR}"

echo "[***] ${STAGE} - Processing ${CONTAINER}"
## IF container has override logic, disregard further checks
if [[ -z "${COMMON_LOADED}" &&  -e "${CONTAINER}.${STAGE}" && -x "${CONTAINER}.${STAGE}" ]]; then
	export COMMON_LOADED="true"
        echo "[***] ${STAGE} - Stage was overridden for container ${CONTAINER}"
        bash ${CONTAINER}.${STAGE}
        exit $?
fi

git diff --quiet --exit-code HEAD^ -- ${CONTAINER}.*
if [[ $? -ne 1 && -z "${LAKKRIS_OVERRIDE}" ]]; then
        echo "[***] ${STAGE} - Exiting early, '${CONTAINER}' objects didn't change."
        exit 0
fi
