#!/bin/bash
function listDockerTags() {
        local repo=${1}
        local size=25
        local page=1
        [ -z "${repo}" ] && echo "Usage: listTags <repoName>" 1>&2 && return 1
        CONT=1
        NEXT="https://hub.docker.com/v2/repositories/${repo}/tags?n=${size}&page=${page}"
        while [[ ${CONT} -eq 1 ]]; do
                RESULT=$(curl "${NEXT}" 2>/dev/null|jq -c --raw-output '.')
                echo ${RESULT} | jq -r '.results[].name' | sort -rV >> /tmp/versions
                NEXT=$(echo ${RESULT} | jq -r '.next')
                if [[ -z "${NEXT}" || "${NEXT}" == "null" ]]; then
                        CONT=0
                else
                        sleep 1s
                fi
        done
        sort -V /tmp/versions
        rm /tmp/versions
}
listDockerTags "${1}"
