#!/usr/bin/with-contenv bash
if [[ ! -d /config/shinobi ]]; then
	mkdir /config/shinobi
fi
# Base shinobi
for x in 'conf' 'super'; do
	if [[ ! -e /config/shinobi/${x}.json ]]; then
		cp /opt/shinobi/${x}.sample.json /config/shinobi/${x}.json
	fi
	if [[ ! -e /opt/shinobi/${x}.json ]]; then
		ln -s /config/shinobi/${x}.json /opt/shinobi/${x}.json
	fi
done

# Motion
#if [[ ! -e /config/shinobi/motion.conf ]]; then
#	cp /opt/shinobi/plugins/motion/conf.sample.json /config/shinobi/motion.json
#fi
#if [[ ! -e /opt/shinobi/plugins/motion/conf.json ]]; then
#	ln -s /config/shinobi/motion.json /opt/shinobi/plugins/motion/conf.json
#fi

PWD=$(pwd)
cd /opt/shinobi && git checkout libs/uploaders && git pull -q && sed -i "s/'public-read'/'private'/g" libs/uploaders/*.js
cd $PWD

if [[ ! -d /dev/shm/streams ]]; then
	mkdir -p /dev/shm/streams
fi

chown -R abc:abc \
	/opt/shinobi

chown -R abc:abc \
	/config/shinobi /opt/shinobi /dev/shm/streams
